### ISSUE TITLE
After using/setting <select sketch> feature, project fails to compile after re-opening VS Code

### ISSUE THREAD

**Issue by github-dodt** [Z-Wave-Me/Z-Uno-VSCode-Plugin#3]
When using the <select sketch> feature from within the VS Code Z-Uno extension initially everything works fine. After closing VS Code and re-opening the project within VS Code functions like: **Z-Uno: Verify (CXtrl+Alr+R)** no longer work and an error is reporterd: **Cannot read properties of undefined (reading 'core')**. 

Removing the newly created file **.vscode/zuno.json** seems to fix the issue...

**Comment by amatilda** [comment]
fix - v0.2.11
